@startuml

title Attack

actor User
participant Fight
participant Player
participant Alien
participant Weapon

User -> Fight : attack
Fight -> Player : attack()
opt
    Player -> Weapon : calculateDamage()
    return damage
end
Player --> Fight : playerAttack
Fight -> Alien : takeDamage(playerAttack)
Fight -> User : displayDamage

@enduml