@startuml

title Add Item

actor User
participant Story
participant Player
participant Item
participant Bag
participant Room

User -> Story : addItem
Story -> Player : addItem(item)
Player -> Item : getWeight()
return weight
alt currentWeight + weight <= MAX_WEIGHT
    Player -> Bag : add(item)
    Player -> Bag : updateCurrentWeight
    Player --> Story : success
    Story -> Room : removeItem(item)
else currentWeight + weight > MAX_WEIGHTT
    Player --> User : Error(bag full)
    Player --> Story : failure
end

@enduml