@startuml

title Collect Item

actor User
participant Player
participant Item
participant Bag
participant RoomList


User -> Player : addItem(item)
Player -> Item : getWeight()
return weight
alt currentWeight + weight <= MAX_WEIGHT
    Player -> RoomList : removeItem(item, currentRoom)
    Player -> Bag : add(item)
    Player -> Player : updateCurrentWeight
else currentWeight + weight > MAX_WEIGHTT
    Player --> User : Error(bag full)
end

@enduml