@startuml

title Defend

actor User
participant Fight
participant Player
participant Shield
participant Alien

User -> Fight : defend
Fight -> Alien : attack()
return damage
Fight -> Player : defend(damage)
Player -> Shield : getDefense()
return defense
Player --> Fight : reducedDamage
Fight -> Player : takeDamage(reducedDamage)
Fight --> User : displayReducedDamage

@enduml