@startuml

title Fight

actor User
participant Fight
participant Player
participant Alien

loop playerHealth and enemyHealth > 0
    Fight -> User : displayOptions
    User -> User : choose
    User --> Fight : choice
    alt choice = attack
        ref over User, Fight : Attack
    else choice = escape
        Fight -> Alien : getEscapeChance()
        return escapeChance
        opt success
            Fight -> Fight : endFight
        end
    else choice = heal
        ref over User, Fight : Heal
    else choice = throwTNT
        ref over User, Fight : ThrowTNT
    else illegal choice
        Fight --> User : Error(invalid choice)
    end
    Fight -> User : displayStatus()
    Fight -> User : displayOptions
        User -> User : choose
        User --> Fight : choice
        alt choice = defend
            ref over User, Fight : Defend
        else choice = elude
            Fight -> Alien : getEludeChance()
            return eludeChance
            alt success
                Fight --> User : displaySuccess
            else failure
                Fight -> Player : takeDamage()
                Fight --> User : displayFailure
            end
        else illegal choice
            Fight --> User : Error(invalid choice)
        end
    Fight -> User : displayStatus()
end
Fight -> User : displayResult

@enduml