@startuml

title Heal

actor User
participant Story
participant Fight
participant Player
participant Bag

User -> Story : heal
Story -> Fight : heal()
Fight -> Player : heal()
Player -> Bag : findItem(medikit)
alt hasMedikit
    return medikit
    Player -> Player : heal()
    Player -> Bag : throwItem(medikit)
    Player --> Fight : success
    Fight --> User : displaySuccess
    Fight -> Fight : alienTurn()
else hasNotMedikit
    Bag --> Player : Error(not found)
    Player --> User : Error( no medKit)
    Player --> Fight : failure
    Fight -> Fight : playerTurn()
end 

@enduml