@startuml

title Heal

actor User
participant Fight
participant Player
participant Bag

User -> Fight : heal
Fight -> Player : heal()
Player -> Bag : search(medikit)
alt hasMedikit
    return medikit
    Player -> Player : heal()
    Player -> Bag : throwItem(medikit)
    Player --> Fight : FULL:HEALTH
    Fight --> User
else hasnotMedikit
    Bag --> Player : Error(not found)
    Player --> Fight : Error(not found)
    Fight --> User : Error(invalid choice)
end 

@enduml