@startuml

title Move

actor User
participant System
participant Player
participant Building
participant RoomList
participant CurrentRoom

User -> System : requestDirection(direction)
System -> Player : getCurrentRoom()
return currentRoom
System -> Building : getAvailableDirections(currentRoom)
loop direction
    Building -> CurrentRoom : getCoordinate()
      return coordinate
    Building -> newCoordinate ** : create(coordinate + direction)
    return newCoordinate
    Building -> RoomList : getRoom(newCoordinate)
    return room
    opt validRoom
        Building -> Building : addDirection
    end
    destroy newCoordinate
end
Building --> System : availableDirections
alt available direction
  System -> CurrentRoom : getCoordinate()
  return coordinate
  System -> RoomList : getRoom(coordinate + direction)
  return room
  System -> Player : setCurrentRoom(room)
  System --> User : displayCurrentRoom
else unavailable direction
  System --> User : Error(invalid move) 
end

@enduml