@startuml

actor User
participant Fight
participant Player
participant Alien
participant Bag
participant TNT

User -> Fight : throwTNT
Fight -> Player : detonateTNT()
Player -> Bag : findItem(TNT)
alt hasTNT
    return TNT
    Player -> TNT : getDamage()
    return damage
    Player -> Bag : throwItem(TNT)
    Player --> Fight : damage
    Fight -> Alien : takeDamage(damage)
    Fight --> User : displayDamage
else hasNotTNT
    Bag --> Player : Error(not found)
    Player --> Fight : Error(not found)
    Fight --> User : Error(invalid command)
end

@enduml