@startuml

title Throw Item

actor User
participant Story
participant Player
participant Bag

User -> Story : throwItem
Story -> Player : throwItem(item)
Player -> Bag : findItem(item)
opt hasItem
  return item
  Player -> Bag : remove(item)
  Player -> Bag : updateCurrentWeight
  Player --> Story : item
  Story --> User : displayItems
end

@enduml