@startuml

title Throw Item

actor User
participant Player
participant Bag
participant RoomList

User -> Player : throwItem(item)
Player -> Bag : findItem(item)
alt hasItem
  return item
  Player -> Bag : remove(item)
  Player -> Bag : updateCurrentWeight
  Player -> RoomList : setItem(item, currentRomm)
  Player --> User : item
else hasNotItem
  Bag --> Player : Error(invalid item)
  Player --> User : Error(item not in bag)
end

@enduml