@startuml

title Design Class Model

abstract class Alien  {
    {abstract} attack() : int
    {abstract} takeDamage(damage:int)
    {abstract} getEscapeChance() : double
    {abstract} getEludeChance() : double
}

class Clicker {
    name_ : String
    health_ : int
    attack_ : int
    attack() : int
    takeDamage(damage:int)
    getEscapeChance() : double
    getEludeChance() : double
}

class Runner {
    name_ : String
    health_ : int
    attack_ : int
    attack() : int
    takeDamage(damage:int)
    getEscapeChance() : double
    getEludeChance() : double
}

class Shambler {
    name_ : String
    health_ : int
    attack_ : int
    attack() : int
    takeDamage(damage:int)
    getEscapeChance() : double
    getEludeChance() : double
}

class Game {
    bHandler : ButtonsHandler
    ui : UI
    vm : VisibilityManager
    building : Building
    player : Player
    story : Story
    newGame()
    loadGame()
}

class ButtonsHandler {
    actionPerformed(e:ActionEvent)
}

class LoadHandler {
    actionPerformed(e:ActionEvent)
}

class Story {
    game : Game
    ui : UI
    vm : VisibilityManager
    player : Player
    building : Building
    defaultSetup()
    setNextPosition(next1:String, next2:String, next3:String, next4:String)
    selectPosition(nextPosition:String)
    map()
    updatePlayerPos()
    proceed()
    checkRoom()
    showItems()
    exitItems()
    throwItems()
    exitThrow()
    getItems() : StringBuilder
    execute(item:String)
    room(nextRow:int, nextColumn:int)
    showDialog(text:String, buttonText:String, actionCommand:String)
    lightOn()
    fightAlien(alien:Alien)
}

class EndingDialog {
    dialogues : List<String>
    iterator : Iterator<String>
    initializeDialogues()
    nextDialogue() : String
}

class IntroductionDialog {
    dialogues : List<String>
    iterator : Iterator<String>
    initializeDialogues()
    nextDialogue() : String
}

class UI {
    bHandler : ButtonsHandler
    homeScreen(gameTitle:String)
    gameScreen()
    newMap()
}

class VisibilityManager {
    ui : UI
    everythingNotVisible()
    showHomeScreen()
    showLoadScreen()
    showMapScreen()
    showDialogScreen()
    showTextScreen()
    showFightScreen()
    showEndScreen()
    showMessage()
}

class Item {
}

class Key {
    name : String
    weight : double
    throwable : boolean
}

class Medikit{
    name : String
    weight : double
    throwable : boolean
}

class Shield {
    name : String
    weight : double
    throwable : boolean
    getDefense() : int
}

class TNT {
    name : String
    weight : double
    throwable : boolean
    getDamage() : int
}

class Torch {
    name : String
    weight : double
    throwable : boolean
    isOn : boolean
    turnOn()
    turnOff()
}

class Weapon {
    name : String
    weight : double
    throwable : boolean
    type_ : String
    minDamage_ : int
    maxDamage_ : int
    calculateDamage() : int
}

class Building {
    rooms : Map<String, Room>
    addRoom(room:Room)
    getRoom(coordinate:String) : Room
    removeRoom(coordinate:String)
    getRooms() : List<Room>
    getAvailableDirections(room:Room) : String
}
 
class Room {
    coordinate : Coordinate
    title : String
    description : String
    iconPath : String
    alien=null : Alien
    is_closed=false : boolean
    items : list<Item>
    is_dark=false : boolean
    addItem(item:Item)
    removeItem(itemToThrow:String)
    removeItem(itemToThrow:Item)
    findItem(itemToFind:String)
    findItem(itemToFind:Item)
    close()
    open()
}

class Coordinate {
    column : int
    row : int
    equals(o:Object) : boolean
    toString() : String
}

class Fight {
    player : Player
    alien : ALien
    ui : UI
    story : Story
    vm : VisibilityManager
    fight()
    playerTurn()
    alienTurn()
    attack()
    run()
    heal()
    tnt()
    defend()
    elude()
    displayStatus()
}

class Player {
    health_ : int
    name_ : String
    bag_ : List<Item>
    currentWeight_=0 : double
    currentRoom_ : Room
    weapon=null : Weapon
    shield=null : Shield
    score_=0 : int
    numKeys = int
    vm : VisibilityManager
    attack() : int
    defend() : int
    heal() : boolean
    takeDamage(damage:int)
    addItem(item:Item)
    throwItem(itemToThrow:Item)
    throwItem(itemToThrow:String)
    findItem(itemToFind:Item)
    findItem(itemToFind:String)
    detonateTNT(int)
    getData() : String
    reset()
}

class AwsConfigReader {
}

class GameSave {
  gson : Gson
  saveGame(player:Player, building:Building)
}

class S3Uploader {
}

Alien <|-- Clicker
Alien <|-- Runner
Alien <|-- Shambler
Fight"1" --> "1"Player : lodges
Fight"1" --> "1"Alien : lodges
Item <|-- Weapon
Item <|-- Medikit
Building o-- Room
Player"1" --> "1"Weapon : wields
Player"1" --> "*"Item : holds
Room"1" --> "*"Item : keeps
Room"1" --> "1"Alien : keeps
Room"1" --> "1"Coordinate : is described by

@enduml