@startuml

object Player {
}

object Profile {
    name
    health
    attack
}

object Game {
}

object GameState {
    Building
    Player
}

object Alien {
}

object AlienType {
  name
  health
  attack
}

object AlienList {
    Clicker
    Runner
    Shambler
}

object Item {
}

object ItemType {
    name
    weight
    throwable
}

object ItemList {
    Key
    MedKit
    Shield
    TNT
    Torch
    Weapon
}

object GameResult {
}

object Scorer {
    score
}

object Building {
}

object Room {
    description
    coordinate
    accessibility
}

object Fight {
}

object Loader {
}

object UI {
}

AlienType"1" -- "*"Alien : describes
AlienList"1" -- "3"AlienType : contains
ItemType"1" -- "*"Item : describes
ItemList"1" -- "6"ItemType : contains
Game"1" -- "*"Alien : spawns
Game"1" -- "*"Item : spawns
Game"1" -- "1"GameResult : generates
Game"1" -- "1"Scorer : updates
GameState"1" -- "1"Game : describes
Player"1" -- "*"Item : holds
Building"1" o-- "13"Room
Room"1" -- "*"Item : detains
Player"1" -- "1"Fight : fights
Alien"1" -- "1"Fight : fights
Profile"1" -- "1"Player : describes
Room"1" --  "0..1"Alien : hosts
Loader"1" -- "1"GameState : saves
UI"1" -- "1"Game : displays

@enduml