@startuml

title System Sequence Diagram

actor User
participant System

User -> System : startGame
loop finish = false
    User -> System : move(direction)
    alt legal direction
        System --> User : displayNewRoom
        opt item
            User -> System : get(item)
            alt item.getWeight() <= freeWeight
                return item
            else item.getWeight() > freeWeight
                System --> User : Error(bag full)
            end
        end
        opt enemy
            loop enemy = true
                alt
                    User -> System : fight()
                    System -> System : fight
                    System --> User : status
                else
                    User -> System : escape()
                    System -> System : enemy = false
                end
            end
            System --> User : result
            opt result = loss
                System -> User : you lose
                System -> System : finish = true
            end
        end
    opt use item
        User -> System : useItem(item)
        alt hasItem
            System -> System : useItem
        else hasNotItem
            System --> User : Error(invalid item)
        end
    end
  else illegal direction
    System --> User : Error(illegal move)
  else finish line
    System -> User : you win
    System -> System : finish = true
  end
end

@enduml