@startuml

title System Sequence Diagram

actor User
participant System

User -> System : start
return displayIntroduction
loop finish = false
    User -> System : move(direction)
    alt legal direction
        System --> User : displayNewRoom
        opt item
            User -> System : get(item)
            alt item.getWeight() <= freeWeight
                return item
            else item.getWeight() > freeWeight
                System --> User : Error(bag full)
            end
        end
        opt enemy
            loop fight = true
                alt playerTurn
                    opt player dead
                        System -> User : game over
                        System -> System : finish = true
                    end
                    System --> User : displayStatus
                    System --> User : displayChoices
                    return choice
                    System -> System
                    System -> User : displayResult
                else alienTurn
                    opt alien dead
                        System -> User : displayVictory
                        System -> System : updateScore
                        System -> System : fight = false
                    end
                    System --> User : displayStatus
                    System --> User : displayChoices
                    return choice
                    System -> System
                    System -> User : displayResult
                end
            end
        end
    opt throw item
        User -> System : throwItem(item)
        return displayItems
    end
    opt exit
        User -> System : exit
        System -> System : finish = true
    end
    opt save and exit
        User -> System : save and exit
        System -> System : save game
        System -> System : finish = true
    end
  else illegal direction
    System --> User : Error(illegal move)
  else finish line
    System -> User : you win
    System -> System : finish = true
  end
end

@enduml