@startuml
class Player {
    -health_: int
    -name_: String
    -bag_: List<Item>
    -currentWeight_: double
    -currentRoom_: Room
    -weapon: Weapon
    -score_: int
    +Player()
    +Player(name: String)
    +getHealth(): int
    +setHealth(health: int): void
    +getName(): String
    +setName(name: String): void
    +getBag(): List<Item>
    +setBag(bag: List<Item>): void
    +getCurrentWeight_(): double
    +setCurrentWeight_(currentWeight: double): void
    +getCurrentRoom_(): Room
    +setCurrentRoom(currentRoom: Room): void
    +getScore(): int
    +setScore(score: int): void
    +setWeapon(weapon: Weapon): void
    +hasWeapon(): boolean
    +attack(): int
    +addItem(item: Item): void
    +throwItem(itemToThrow: Item): Item
    +heal(): void
    +takeDamage(damage: int): void
    +getData(): String
    +reset(): void
}


@enduml